config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :survivalists do
    resources :meetings, only: [:new, :create, :show, :index]
  end
  resources :meetings, only: [:destroy]
  resources :pages, only: [:index, :show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  belongs_to :survivalist
end

app/models/survivalist.rb
class Survivalist < ApplicationRecord
  belongs_to :user
  has_many :meetings
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  has_one :survivalist
  has_many :meetings
  has_one_attached :photo
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit::Authorization

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:city, :name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:city, :name, :photo])
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_user
  before_action :set_survivalist, only: [:index, :new, :create]
  before_action :set_meeting, only: [:destroy]

  def index
    @meetings = Meeting.all
  end

  def show
    @meeting = Meeting.find(params[:id])
    @meeting.user_id = current_user.id
  end

  def new
    @meeting = Meeting.new
  end

  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.user = @user
    @meeting.survivalist = @survivalist
    if @meeting.save
      redirect_to survivalist_meeting_path(@meeting.survivalist_id, @meeting.id), status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @meeting.destroy
    redirect_to pages_path, status: :see_other
  end

  private

  def meeting_params
    params.require(:meeting).permit(:user_id, :survivalist_id, :start_date, :end_date)
  end

  def set_user
    @user = current_user
  end

  def set_survivalist
    @survivalist = Survivalist.find(params[:survivalist_id])
  end

  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :dashboard]
  def home
  end

  def index
    @meetings = Meeting.all
    @survivalists = Survivalist.all
    @meetings = policy_scope(Meeting)
  end

  def show
    @meeting = Meeting.find(params[:id])
    @meeting.user_id = current_user.id
    @survivalist = Survivalist.find(params[:id])
    @meeting = policy_scope(Meeting)
  end
end

app/controllers/survivalists_controller.rb
class SurvivalistsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]
  def index
    if params[:query].present?
      if current_user
        sql_query = "(category ILIKE :query OR city ILIKE :query OR postcode ILIKE :query) AND user_id != :usr"
        @survivalists = Survivalist.where(sql_query, query: "%#{params[:query]}%", usr: current_user.id.to_s)
      else
        sql_query = "(category ILIKE :query OR city ILIKE :query OR postcode ILIKE :query)"
        @survivalists = Survivalist.where(sql_query, query: "%#{params[:query]}%")
      end
    else
      if current_user
        @survivalists = Survivalist.all
        sql_query = "user_id != :usr"
        @survivalists = Survivalist.where(sql_query, usr: current_user.id.to_s)
      else
        @survivalists = Survivalist.all
      end
    end
    @survivalists_all = @survivalists
    @markers = @survivalists_all.geocoded.map do |survivalist|
      {
        lat: survivalist.latitude,
        lng: survivalist.longitude,

        info_window: render_to_string(partial: "info_window", locals: {survivalist: survivalist}),
        image_url: helpers.asset_url("pointer.png")
      }
    end
  end

  def new
    @survivalist = Survivalist.new
  end

  def create
    @survivalist = Survivalist.new(survivalist_params)
    @survivalist.user = current_user
    @survivalist.name = current_user.name
    @survivalist.address = "#{@survivalist.street}, #{@survivalist.postcode} #{@survivalist.city}"
    if @survivalist.save
      redirect_to survivalist_path(@survivalist)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @survivalist = Survivalist.find(params[:id])
  end

  private

  def survivalist_params
    params.require(:survivalist).permit(:name, :category, :skills, :street, :postcode, :city)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentOrDie</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://fonts.googleapis.com/css2?family=Slabo+13px&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Creepster&display=swap" rel="stylesheet">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <div class="d-flex flex-column min-vh-100">
      <%= render 'shared/navbar' %>
      <article class="flex-grow-1 bg-dark">
        <%= yield %>
      </article>
      <%= render 'shared/footer' %>
    </div>
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </body>
</html>

app/views/meetings/new.html.erb
<div class="banner" style="background-image: url(<%= cl_image_path @survivalist.user.photo.key %>">
</div>

<div class="container">
  <div class="row justify-content-center mt-3 mb-5">
    <div class="col-12 col-lg-6">
      <%= link_to "Back to all Survivalists", survivalists_path, class: "btn btn-primary mb-2" %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center mt-1 mb-5">
    <div class="col-12 col-lg-6">
      <h1 class="text-light">Reserve <%= @survivalist.name %></h1>
      <%= simple_form_for [@survivalist, @meeting] do |f| %>
        <%= f.input :start_date, as: :datetime, html5: true %>
        <%= f.input :end_date, as: :datetime, html5: true %>
        <div class="btn btn-danger">
          <%= f.button :submit, class:"text-light" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/meetings/show.html.erb
<div class="container">
  <div class="container-listing text-center">
    <br>
    <h2><strong>Congratulations, your Survivalist has been booked!</strong></h2><br>
    <h3><strong>Booking Details</strong></h3>
    <hr>
    <strong>Start Date: <%= @meeting.start_date %></strong> | <strong>End Date: <%= @meeting.end_date %></strong>

    <h4><strong><%= @meeting.survivalist.name %></strong></h4>
    <p>Location: <%= @meeting.survivalist.street %></p>
    <p><%= @meeting.survivalist.city %></p>

    <div><br>
      <%= cl_image_tag @meeting.survivalist.user.photo.key, alt: "Your Specialist photo", width: "300", class: "booking-image" %>
    </div>
    <br>
    <p><%= link_to "Check dashboard", pages_path %></p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner-home" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://scitechdaily.com/images/Bruning-City-Apocalypse-Concept.jpg);">

  <div class="container" id="glitch">
    <h1>Want to live? Find your <%= link_to "SURVIVALIST", survivalists_path, class: "now-button" %>.</h1>
    <h1>Are you a bad-ass Survivalist? Prove it and Register <%= link_to "HERE", new_survivalist_path(@survivalist), class: "now-button" %>.</h1>
  <div>

  <div class="container-shit">
    <%= form_tag survivalists_path, method: :get do %>
    <%= text_field_tag :query, params[:query], placeholder: "Don't die..."%>
    <div class="search"></div>
    <% end %>
  </div>

</div>

app/views/pages/index.html.erb
<div class="p-3 mb-2 bg-dark text-light">
  <div class="gradient">
    <div class="container">
      <div class="App">
        <h2 class="lost"> &darr; My Survivalist! &darr;</h2>
      </div>
      <% if @meetings.size > 0 %>
      <div class="cards">
        <% @meetings.each do |meeting| %>
          <div class="card-trip">
            <%= cl_image_tag meeting.survivalist.user.photo.key %>
            <div class="card-trip-infos">
              <h2><%= meeting.survivalist.name %></h2>
              <p>Category: <%= meeting.survivalist.category %></p>
              <p>Skill: <%= meeting.survivalist.skills %></p>
            </div>
            <div class="card-trip-infos">
                <p>From <span><em><%= meeting.start_date.strftime("%d.%m.%Y %H:%M") %></em></span>
                <br />to <span><em><%= meeting.end_date.strftime("%d.%m.%Y %H:%M") %></em></p></span>
                <p><strong>£222999.99/day</strong></p>
                <% if policy(meeting).destroy? %>
                  <%= link_to raw("<i class=\"fa-solid fa-trash-can\"></i>"), meeting_path(meeting), data: {turbo_method: :delete} %>
                <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <% else %>
      <h5 class="text-light text-center mt-5"><em>No meetings ahead</em></h5>
      <% end %>
    </div>
    <p class="text-center mt-3"><%= link_to "Back to Homepage", root_path, class: "text-center" %></p>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Goodluck out there.... <i class="fa-sharp fa-solid fa-skull">  &copy <span>2022 Rent-Or-Die</span> </i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon">
  <div class="container-fluid nav-items">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dbybmxt1u/image/upload/v1669199843/rentordie_crj9mw.png" %>
    <% end %>

    <button class="navbar-toggler nav-icon" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse nav-items" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active nav-item-spacing py-1 me-2">
          <%= link_to "Home", root_path, class: "nav-link text-light" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", pages_path, class: "dropdown-item" %>
              <%= link_to "Book a Survivalist", survivalists_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item py-1">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-light" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/survivalists/_info_window.html.erb
<h2><%= survivalist.name %></h2>

app/views/survivalists/index.html.erb
<div class="p-3 mb-2 text-white">
  <div class="gradient">
    <div class="container">

    <div class="App">
      <h2 class="lost"> &darr; Choose Your Survivalist! &darr;</h2>
    </div>
      <div class="my-5 grid-display">

        <div class="container cards mb-4">
          <% @survivalists.each do |survivalist| %>
            <%= link_to survivalist_path(survivalist) do %>
              <div class="card-trip rounded">
                <%= cl_image_tag survivalist.user.photo.key %>
                <div class="card-trip-infos">
                  <div>
                    <h2 text-light><%= survivalist.name %></h2>
                    <p text-light><%= survivalist.category %></p>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>

        <div class="container">
          <div data-controller="map"
               data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
               data-map-markers-value="<%= @markers.to_json %>"
               class="rounded map-responsive">
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/survivalists/new.html.erb
<div class="p-3 mb-2 bg-dark text-white">
<div class="banner" style="background-image: url(https://9to5toys.com/wp-content/uploads/sites/5/2022/01/forever-skies-no-logo.jpg)">


</div>
  <div class="container">
    <div class="new-survivalist">
      <h1> <strong>&darr; Register a Survivalist Profile! &darr;</strong> </h1>
      <%= simple_form_for(@survivalist) do |f| %>
        <%= f.input :category, as: :select, collection: ["Engineer", "Medical", "Destroyer", "Cook", "Hunter"] %>
        <%= f.input :skills %>
        <%= f.input :street %>
        <%= f.input :postcode %>
        <%= f.input :city, input_html: { value: current_user.city } %>
        <%= f.submit "Submit", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/survivalists/show.html.erb
<div class="container">
  <div class="row justify-content-center my-4">
    <div class="col-12 col-lg-6">
      <div class="card-trip" id="big-img">
        <%= cl_image_tag @survivalist.user.photo.key %>
        <h3 class="text-center mt-4"><%= @survivalist.name %></h3>
        <div class="card-trip-infos d-flex justify-content-evenly">
          <div>
            <p><strong>Category:</strong> <%= @survivalist.category %></p>
            <p><strong>Skill:</strong> <%= @survivalist.skills %></p>
          </div>

          <div>
            <p><strong>City:</strong> <%= @survivalist.city %></p>
            <p><strong>Postcode:</strong> <%= @survivalist.postcode %></p>
          </div>
          <h2 class="card-trip-pricing">£222999.99/day</h2>

        </div>
      </div>
    </div>
  </div>
  <div class="my-4 text-center">
    <p><%= link_to "Reserve Survivalist", new_survivalist_meeting_path(@survivalist), class:"btn btn-danger text-light" %></p>
    <%= link_to "Back to all survivalists", survivalists_path, class: "btn btn-success text-white mb-2" %>
  </div>
</div>